### ISSUE TITLE
switch不可用

### ISSUE THREAD

**Issue by gwhzh21** [layui/laytpl#13]
{{# switch (d.orders){}}}这样写没有问题。
{{# switch (d.orders){}}
{{#}}}
始终报错。Laytpl Error：SyntaxError: Unexpected token ;

**Comment by ydq** [comment]
感觉还不如直接用if-else 代替 switch-case呢

**Comment by sentsin** [comment]
参考：http://www.layui.com/doc/modules/laytpl.html
