### ISSUE TITLE
关于一些疑问

### ISSUE THREAD

**Issue by yyman001** [layui/laytpl#2]
1.关于demo中出现的`d.list.xx`中的`d`不知道是别名还是什么,没有具体说明,所以在使用的时候不清楚是怎么表达数据的调用~
2.如果通过跨域返回的数据,获取之后是数组对象类型,`[{},{}]`,也没有具体例子,因为官网只提供一种{}方式来展示的数据,在实际开发测试中有点不一样,所以测试不通过,有点疑问
3.如果输出的是一个属性值,官网没有给出这种情况`<img class="game-icon" src="{{ d.result[i].iconUrl }}" alt="">` 到底这种情况中,双引号是否对引擎模板有影响?获取需要使用转义?
   这是我在使用中的一些疑问,可能比较低级的问题~

**Comment by sentsin** [comment]
1、d是你传入的对象，比如你传入的var date = {a: 1}; laytpl(temp).render(date, callback); d即date。
2、你只要把接收到的对象传入给laytpl即可。
3、双引号不会对引擎有影响，都有做处理。

**Comment by bravility** [comment]
mark
