### ISSUE TITLE
#号处理

### ISSUE THREAD

**Issue by ssy341** [layui/laytpl#22]
```javascript
{{ d.anyPromotion==1?"<a href='#anyPromoteSelect' data-groupPro>组合</a>":"" }}
```

`#anyPromoteSelect` 解析会有问题，会当做js代码去解析，用什么可以替代#？

**Comment by sentsin** [comment]
改成 
`
   {{# if(d.anyPromotion==1){  }} <a href='#anyPromoteSelect' data-groupPro>组合</a> {{# } }}
`

**Comment by ssy341** [comment]
@sentsin 谢谢你的回答，也就是从语法上尽量避开这种写法，当时没有想到
