### ISSUE TITLE
文档能否写的更详细点？

### ISSUE THREAD

**Issue by spaceliner** [layui/laytpl#23]
对于一个初学者，看的云里雾里，完全不知道这几个步骤写在那里，如何传后台的JSON数据，可不可以写一个Demo什么的也好参考一下，谢谢

**Comment by sentsin** [comment]
嗯，layui 2.0发布后，laytpl的文档也会重写。感谢建议

**Comment by sentsin** [comment]
http://www.layui.com/doc/modules/laytpl.html
