### ISSUE TITLE
请问模板代码是不是只能写到html中

### ISSUE THREAD

**Issue by pakey** [layui/laytpl#4]
采用&lt;script id="demo" type="text/html">&lt;/script>这样的写到HTML中，
如果我相直接把代码写到js中有没有比较好的方案呢
var tpl=*****;
laytpl(tpl).render(data, function(html){});
这样么？

**Comment by sentsin** [comment]
不一定，可以写在任意地方。。。

**Comment by zhujunel** [comment]
能不能用引用js的方式，引用到页面里面来，具体怎么做呢

**Comment by pakey** [comment]
var a='模板代码'
这样引入就行了

**Comment by zhujunel** [comment]
回复的好快啊，好的试试~

**Comment by zhujunel** [comment]
@pakey 兄弟还有没有其他的方式引入模板呢，用var a='模板代码'，好乱啊，没有一点结构，一长串字符串~
