### ISSUE TITLE
一些建议...

### ISSUE THREAD

**Issue by juzhishang** [layui/laytpl#5]
既然laytpl支持了模板缓存，为什么不在Tpl.pt.render方法结尾return this呢
var mgtpl=laytpl(tpl).render(data, function(render){});//这样貌似更省事

希望能扩展helper方法，一些列表数据免不了会有日期、金额、数字修饰什么的。

**Comment by sentsin** [comment]
模版里面可以写任意的js方法

**Comment by hustcer** [comment]
@sentsin Thanks for the great work, but have not been updated for quite a long time ...
Is it still be maintained ?

**Comment by sentsin** [comment]
@hustcer  Yeah! 今后laytpl只会在layui体系中升级，而不在作为一个独立组件存在。

**Comment by hustcer** [comment]
@sentsin `layui`什么时候发布呢？主力开发就你一个么？
